### ISSUE TITLE
can't use strace because of docker privileges

### ISSUE THREAD

**Issue by othmane39** [cboin/re_lab#1]
i can't use strace ltrace on process because docker have some features that deny this

**Comment by cboin** [comment]
Thank you for reporting. I will take a look soon.

**Comment by cboin** [comment]
After diving into the docker official documentation. You should disable the security labeling. 
Can you try by running your container using the following flag: ```--privileged``` ?

The command for running your container should look like this: 
```bash
$ docker run -it \
    --privileged \
    -v $(pwd)/share_ro:/share_ro:ro \
    -v $(pwd)/share_rw:/share_rw \
    re_lab
```

I've updated the README.md file according to your issue.
The corresponding docker documentation's page: [Security Configuration](https://docs.docker.com/engine/reference/run/#security-configuration)

Thanks you again for your issue,
Regards, 
Clément Boin

**Comment by othmane39** [comment]
Thanks !
